name: Docker Build/Publish Image - ARMv7

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/hueshift2
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up QEMU Dependency
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        if: success()
        id: prepare
        run: | 
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_REGISTRY}/${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Docker Login
        if: success()
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Docker Image Tag
        if: success()
        id: extract_branch
        shell: bash
        run: |
          branchName=${{ github.ref_name }}
          if [ $branchName != 'master' ]; then image_tag='staging'; else image_tag='latest'; fi
          echo "{tag}={$(echo $image_tag)}" >> $GITHUB_OUTPUT

      #- name: Run Buildx - Push Image
      #  if: success()
      #  run: |
      #    docker buildx build \
      #    --platform ${{ steps.prepare.outputs.docker_platform }} \
      #    --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.extract_branch.outputs.tag}} \
      #    --file ./Dockerfile \
      #    --output type=image,push=true .



