name: Docker Build/Publish Image - ARMv7

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: mholubinka1/hueshift2
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up QEMU Dependency
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        if: success()
        id: prepare
        run: | 
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}

      - name: Docker Login
        if: success()
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Run Buildx - Push Image
      #  if: success()
      #  run: |
      #    docker buildx build \
      #    --platform ${{ steps.prepare.outputs.docker_platform }} \
      #    --tag ${{ steps.prepare.outputs.docker_image }}:latest \
      #    --file ./Dockerfile \
      #    --output type=image,push=true .



