name: Docker Build/Publish Image - ARMv7

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  ARMv7_Image_Build_and_Push:
    runs-on: [ ARMv7 ]
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/hueshift2
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Set Up QEMU Dependency
      #  uses: docker/setup-qemu-action@v1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        if: success()
        id: prepare
        run: | 
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_REGISTRY}/${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Docker Login
        if: success()
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Docker Image Tag
        if: success()
        id: tag
        shell: bash
        run: |
          branchName=${{ github.ref_name }}
          if [ $branchName != 'master' ]; then image_tag='staging'; else image_tag='latest'; fi
          echo "tag=$(echo $image_tag)" >> $GITHUB_OUTPUT

      - name: Docker Build And Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.prepare.outputs.docker_image }}:${{ steps.tag.outputs.tag }}




