name: Docker Build/Publish Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: index.docker.io/mholubinka1/hueshift2
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    
    - name: Prepare
      if: success()
      id: prepare
      run: | 
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}
    
    - name: Docker Login
      if: success()
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Run Buildx - Push Image
      if: success()
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
        --file ./Dockerfile \
        --output type=image,push=true .